apiVersion: v1
kind: Namespace
metadata:
  name: vnc-pod-1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vnc-deployment-1
  namespace: vnc-pod-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vnc-1
  template:
    metadata:
      labels:
        app: vnc-1
    spec:
      containers:
      - name: vnc-container-1
        image: rafiqrock2003/ubuntu22-gui-rafik:v1
        ports:
        - containerPort: 5901

---

apiVersion: v1
kind: Service
metadata:
  name: vnc-service-1
  namespace: vnc-pod-1
spec:
  selector:
    app: vnc-1
  ports:
  - protocol: TCP
    port: 5901
    targetPort: 5901
  type: LoadBalancer

