apiVersion: v1
kind: Service
metadata:
  name: vnc-service
  namespace: vnc1
spec:
  selector:
    app: vnc-pod-1
  ports:
  - name: vnc-port
    protocol: TCP
    port: 5901         # Port exposed by the service
    targetPort: 5901   # Port on the pods that the service forwards to
  - name: vnc-ssh
    protocol: TCP
    port: 22
    targetPort: 22
  type: NodePort

