apiVersion: v1
kind: Namespace
metadata:
  name: vnc-pod

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vnc-deployment
  namespace: vnc-pod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vnc
  template:
    metadata:
      labels:
        app: vnc
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - worker-node-2
      containers:
      - name: vnc-container
        image: rafiqrock2003/ubuntu22-gui-rafik:v1
        ports:
        - containerPort: 5901

---

apiVersion: v1
kind: Service
metadata:
  name: vnc-service
  namespace: vnc-pod
spec:
  selector:
    app: vnc
  ports:
  - protocol: TCP
    port: 5901
    targetPort: 5901
  type: LoadBalancer
  loadBalancerIP: 192.168.21.15

